from typing import Any


def transform(rows: list[dict[str, Any]]):
    return rows


schema = [
    {"name": "vertical", "type": "STRING"},
    {"name": "name", "type": "STRING"},
    {"name": "Elf", "type": "STRING"},
    {"name": "user_platform", "type": "STRING"},
    {"name": "user_state", "type": "STRING"},
    {"name": "user_state_changed_at", "type": "TIMESTAMP"},
    {"name": "user_occurrence", "type": "STRING"},
    {"name": "user_paying_state", "type": "STRING"},
    {"name": "user_paying_state_changed_at", "type": "TIMESTAMP"},
    {"name": "user_last_activity_time", "type": "TIMESTAMP"},
    {"name": "user_last_paying_activity_time", "type": "TIMESTAMP"},
    {"name": "user_ltv_cents", "type": "NUMERIC"},
    {"name": "user_ltv_currency", "type": "STRING"},
    {"name": "reason", "type": "STRING"},
    {"name": "price_product", "type": "NUMERIC"},
    {"name": "price_product_currency", "type": "STRING"},
    {"name": "price_tax", "type": "NUMERIC"},
    {"name": "price_tax_currency", "type": "STRING"},
    {"name": "price_shipping", "type": "NUMERIC"},
    {"name": "price_shipping_currency", "type": "STRING"},
    {"name": "price_customs", "type": "NUMERIC"},
    {"name": "price_customs_currency", "type": "STRING"},
    {"name": "cost_product", "type": "NUMERIC"},
    {"name": "cost_product_currency", "type": "STRING"},
    {"name": "cost_shipping", "type": "NUMERIC"},
    {"name": "cost_shipping_currency", "type": "STRING"},
    {"name": "cost_customs", "type": "NUMERIC"},
    {"name": "cost_customs_currency", "type": "STRING"},
    {"name": "elves_fee", "type": "NUMERIC"},
    {"name": "elves_shipping", "type": "NUMERIC"},
    {"name": "elves_fee_refunded", "type": "STRING"},
    {"name": "elves_shipping_refunded", "type": "STRING"},
    {"name": "elves_tax", "type": "NUMERIC"},
    {"name": "elves_currency", "type": "STRING"},
    {"name": "headline", "type": "STRING"},
    {"name": "id", "type": "NUMERIC"},
    {"name": "title", "type": "STRING"},
    {"name": "status", "type": "STRING"},
    {"name": "completed_at", "type": "TIMESTAMP"},
    {"name": "user_id", "type": "NUMERIC"},
    {"name": "vertical_id", "type": "NUMERIC"},
    {"name": "initial_message_id", "type": "NUMERIC"},
    {"name": "urgent", "type": "NUMERIC"},
    {"name": "request_count", "type": "NUMERIC"},
    {"name": "created_at", "type": "TIMESTAMP"},
    {"name": "updated_at", "type": "TIMESTAMP"},
    {"name": "marked_as_case", "type": "NUMERIC"},
    {"name": "creator_id", "type": "NUMERIC"},
    {"name": "description", "type": "STRING"},
    {"name": "branch_id", "type": "NUMERIC"},
    {"name": "pickup_address_id", "type": "NUMERIC"},
    {"name": "delivery_address_id", "type": "NUMERIC"},
    {"name": "form_status", "type": "STRING"},
    {"name": "metadata_json", "type": "STRING"},
    {"name": "user_country_origin", "type": "STRING"},
    {"name": "user_lang", "type": "STRING"},
]
