from elves.pipeline import interface

pipeline = interface.Pipeline(
    name="Analytics",
    url="https://api.elvesapp.com/api/utils/analytics/requests",
    transform=lambda rows: [
        {
            "vertical": row.get("vertical"),
            "merchant": row.get("merchant"),
            "name": row.get("name"),
            "Elf": row.get("Elf"),
            "user_platform": row.get("user_platform"),
            "user_state": row.get("user_state"),
            "user_state_changed_at": row.get("user_state_changed_at"),
            "user_occurrence": row.get("user_occurrence"),
            "user_paying_state": row.get("user_paying_state"),
            "user_paying_state_changed_at": row.get("user_paying_state_changed_at"),
            "user_last_activity_time": row.get("user_last_activity_time"),
            "user_last_paying_activity_time": row.get("user_last_paying_activity_time"),
            "user_ltv_cents": row.get("user_ltv_cents"),
            "user_ltv_currency": row.get("user_ltv_currency"),
            "reason": row.get("reason"),
            "price_product": row.get("price_product"),
            "price_product_currency": row.get("price_product_currency"),
            "price_tax": row.get("price_tax"),
            "price_tax_currency": row.get("price_tax_currency"),
            "price_shipping": row.get("price_shipping"),
            "price_shipping_currency": row.get("price_shipping_currency"),
            "price_customs": row.get("price_customs"),
            "price_customs_currency": row.get("price_customs_currency"),
            "cost_product": row.get("cost_product"),
            "cost_product_currency": row.get("cost_product_currency"),
            "cost_shipping": row.get("cost_shipping"),
            "cost_shipping_currency": row.get("cost_shipping_currency"),
            "cost_customs": row.get("cost_customs"),
            "cost_customs_currency": row.get("cost_customs_currency"),
            "elves_fee": row.get("elves_fee"),
            "elves_shipping": row.get("elves_shipping"),
            "elves_fee_refunded": row.get("elves_fee_refunded"),
            "elves_shipping_refunded": row.get("elves_shipping_refunded"),
            "elves_tax": row.get("elves_tax"),
            "elves_currency": row.get("elves_currency"),
            "headline": row.get("headline"),
            "id": row.get("id"),
            "title": row.get("title"),
            "status": row.get("status"),
            "completed_at": row.get("completed_at"),
            "user_id": row.get("user_id"),
            "vertical_id": row.get("vertical_id"),
            "initial_message_id": row.get("initial_message_id"),
            "urgent": row.get("urgent"),
            "request_count": row.get("request_count"),
            "created_at": row.get("created_at"),
            "updated_at": row.get("updated_at"),
            "marked_as_case": row.get("marked_as_case"),
            "creator_id": row.get("creator_id"),
            "description": row.get("description"),
            "branch_id": row.get("branch_id"),
            "pickup_address_id": row.get("pickup_address_id"),
            "delivery_address_id": row.get("delivery_address_id"),
            "form_status": row.get("form_status"),
            "metadata_json": row.get("metadata_json"),
            "user_country_origin": row.get("user_country_origin"),
            "user_lang": row.get("user_lang"),
        }
        for row in rows
    ],
    schema=[
        {"name": "vertical", "type": "STRING"},
        {"name": "merchant", "type": "STRING"},
        {"name": "name", "type": "STRING"},
        {"name": "Elf", "type": "STRING"},
        {"name": "user_platform", "type": "STRING"},
        {"name": "user_state", "type": "STRING"},
        {"name": "user_state_changed_at", "type": "TIMESTAMP"},
        {"name": "user_occurrence", "type": "STRING"},
        {"name": "user_paying_state", "type": "STRING"},
        {"name": "user_paying_state_changed_at", "type": "TIMESTAMP"},
        {"name": "user_last_activity_time", "type": "TIMESTAMP"},
        {"name": "user_last_paying_activity_time", "type": "TIMESTAMP"},
        {"name": "user_ltv_cents", "type": "NUMERIC"},
        {"name": "user_ltv_currency", "type": "STRING"},
        {"name": "reason", "type": "STRING"},
        {"name": "price_product", "type": "NUMERIC"},
        {"name": "price_product_currency", "type": "STRING"},
        {"name": "price_tax", "type": "NUMERIC"},
        {"name": "price_tax_currency", "type": "STRING"},
        {"name": "price_shipping", "type": "NUMERIC"},
        {"name": "price_shipping_currency", "type": "STRING"},
        {"name": "price_customs", "type": "NUMERIC"},
        {"name": "price_customs_currency", "type": "STRING"},
        {"name": "cost_product", "type": "NUMERIC"},
        {"name": "cost_product_currency", "type": "STRING"},
        {"name": "cost_shipping", "type": "NUMERIC"},
        {"name": "cost_shipping_currency", "type": "STRING"},
        {"name": "cost_customs", "type": "NUMERIC"},
        {"name": "cost_customs_currency", "type": "STRING"},
        {"name": "elves_fee", "type": "NUMERIC"},
        {"name": "elves_shipping", "type": "NUMERIC"},
        {"name": "elves_fee_refunded", "type": "STRING"},
        {"name": "elves_shipping_refunded", "type": "STRING"},
        {"name": "elves_tax", "type": "NUMERIC"},
        {"name": "elves_currency", "type": "STRING"},
        {"name": "headline", "type": "STRING"},
        {"name": "id", "type": "NUMERIC"},
        {"name": "title", "type": "STRING"},
        {"name": "status", "type": "STRING"},
        {"name": "completed_at", "type": "TIMESTAMP"},
        {"name": "user_id", "type": "NUMERIC"},
        {"name": "vertical_id", "type": "NUMERIC"},
        {"name": "initial_message_id", "type": "NUMERIC"},
        {"name": "urgent", "type": "NUMERIC"},
        {"name": "request_count", "type": "NUMERIC"},
        {"name": "created_at", "type": "TIMESTAMP"},
        {"name": "updated_at", "type": "TIMESTAMP"},
        {"name": "marked_as_case", "type": "NUMERIC"},
        {"name": "creator_id", "type": "NUMERIC"},
        {"name": "description", "type": "STRING"},
        {"name": "branch_id", "type": "NUMERIC"},
        {"name": "pickup_address_id", "type": "NUMERIC"},
        {"name": "delivery_address_id", "type": "NUMERIC"},
        {"name": "form_status", "type": "STRING"},
        {"name": "metadata_json", "type": "STRING"},
        {"name": "user_country_origin", "type": "STRING"},
        {"name": "user_lang", "type": "STRING"},
    ],
)
